/**
 * MorningBrief — Personalized daily briefing agent.
 *
 * Checks weather for Smyrna GA, reads calendar, summarizes priorities
 * from memory, and speaks the briefing aloud via TTS.
 *
 * Auto-generated by LearnNewAgent on 2026-02-28 03:02.
 * Enhanced with multi-agent chaining.
 */

import fs from 'fs/promises';
import path from 'path';
import os from 'os';

export function createAgent(BasicAgent) {

  // Lazy-load sibling agents from the built-in agents directory
  let _webAgent = null;
  let _memoryAgent = null;
  let _ttsAgent = null;

  async function getBuiltinAgent(name) {
    const agentsDir = path.join(os.homedir(), '.openrappter', 'typescript', 'dist', 'agents');
    const mod = await import(path.join(agentsDir, `${name}Agent.js`));
    for (const key of Object.keys(mod)) {
      if (typeof mod[key] === 'function' && mod[key].prototype instanceof BasicAgent) {
        return new mod[key]();
      }
    }
    return null;
  }

  class MorningBriefAgent extends BasicAgent {
    constructor() {
      const metadata = {
        name: 'MorningBrief',
        description: 'Daily briefing: weather, calendar, priorities from memory, spoken via TTS.',
        parameters: {
          type: 'object',
          properties: {
            query: { type: 'string', description: 'Optional override (default runs full briefing).' },
            location: { type: 'string', description: 'Weather location (default: Smyrna GA).' },
            speak: { type: 'string', description: 'Set to "false" to skip TTS.' }
          },
          required: []
        }
      };
      super('MorningBrief', metadata);
    }

    async perform(kwargs) {
      const location = kwargs.location || 'Smyrna GA';
      const skipTTS = String(kwargs.speak).toLowerCase() === 'false' ||
                      String(kwargs.query).toLowerCase().includes('speak:false');
      const sections = [];
      const now = new Date();
      const dayName = now.toLocaleDateString('en-US', { weekday: 'long' });
      const dateFmt = now.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });

      sections.push(`Good morning! It's ${dayName}, ${dateFmt}.`);

      // 1. Weather via Web search
      try {
        if (!_webAgent) _webAgent = await getBuiltinAgent('Web');
        if (_webAgent) {
          const weatherResult = await _webAgent.execute({
            action: 'search',
            query: `weather ${location} today`
          });
          const parsed = JSON.parse(weatherResult);
          const weatherText = parsed?.result || parsed?.results?.[0]?.snippet || 'Weather data retrieved.';
          sections.push(`Weather in ${location}: ${String(weatherText).slice(0, 300)}`);
        } else {
          sections.push('Weather: Web agent unavailable.');
        }
      } catch (e) {
        sections.push(`Weather: ${e.message || 'unavailable'}`);
      }

      // 2. Calendar — try common locations
      let calendarText = '';
      const calPaths = [
        path.join(os.homedir(), 'calendar.md'),
        path.join(os.homedir(), 'calendar.txt'),
        path.join(os.homedir(), 'Documents', 'calendar.md'),
        path.join(os.homedir(), '.openrappter', 'calendar.md'),
      ];
      for (const p of calPaths) {
        try {
          const content = await fs.readFile(p, 'utf-8');
          calendarText = content.slice(0, 500);
          break;
        } catch { /* next */ }
      }
      if (calendarText) {
        sections.push(`Calendar: ${calendarText}`);
      } else {
        sections.push('No calendar file found — consider creating ~/calendar.md.');
      }

      // 3. Priorities from Memory
      try {
        if (!_memoryAgent) _memoryAgent = await getBuiltinAgent('Memory');
        if (_memoryAgent) {
          const memResult = await _memoryAgent.execute({
            action: 'recall',
            query: 'priorities tasks today important'
          });
          const parsed = JSON.parse(memResult);
          const memText = parsed?.result || parsed?.memories || 'No priority memories found.';
          sections.push(`Priorities: ${String(memText).slice(0, 500)}`);
        } else {
          sections.push('Priorities: Memory agent unavailable.');
        }
      } catch (e) {
        sections.push(`Priorities: ${e.message || 'none found'}`);
      }

      // Compose briefing
      const briefing = sections.join('\n\n');

      // 4. Speak via TTS (unless disabled)
      let ttsStatus = 'skipped';
      if (!skipTTS) {
        try {
          if (!_ttsAgent) _ttsAgent = await getBuiltinAgent('TTS');
          if (_ttsAgent) {
            const ttsResult = await _ttsAgent.execute({
              action: 'speak',
              text: briefing.slice(0, 800)
            });
            ttsStatus = 'spoken';
          }
        } catch (e) {
          ttsStatus = `TTS error: ${e.message}`;
        }
      }

      return JSON.stringify({
        status: 'success',
        briefing,
        sections: {
          greeting: sections[0],
          weather: sections[1],
          calendar: sections[2],
          priorities: sections[3],
        },
        tts: ttsStatus,
        data_slush: this.slushOut({
          signals: {
            location,
            sections_count: sections.length,
            tts_enabled: !skipTTS,
            date: dateFmt,
          }
        })
      });
    }
  }

  return MorningBriefAgent;
}
