"""Tests for LearnNewAgent - agent generation, naming, and management."""

import json
import pytest
from pathlib import Path

from openrappter.agents.learn_new_agent import LearnNewAgent


@pytest.fixture
def agent(tmp_path):
    a = LearnNewAgent()
    a.agents_dir = tmp_path
    return a


# --- Metadata ---

class TestLearnNewMetadata:
    def test_name(self):
        agent = LearnNewAgent()
        assert agent.name == "LearnNew"

    def test_actions_enum(self):
        agent = LearnNewAgent()
        actions = agent.metadata["parameters"]["properties"]["action"]["enum"]
        assert set(actions) == {"create", "list", "delete"}


# --- Name generation & sanitization ---

class TestNaming:
    def test_sanitize_name_basic(self, agent):
        assert agent._sanitize_name("MyAgent") == "MyAgent"

    def test_sanitize_removes_special_chars(self, agent):
        assert agent._sanitize_name("my-agent!") == "Myagent"

    def test_sanitize_starts_with_number(self, agent):
        assert agent._sanitize_name("123bot") == "Agent123bot"

    def test_sanitize_empty_returns_custom(self, agent):
        assert agent._sanitize_name("") == "Custom"

    def test_to_snake_case(self, agent):
        assert agent._to_snake_case("MyAgent") == "my_agent"
        assert agent._to_snake_case("HTTPClient") == "http_client"
        assert agent._to_snake_case("Simple") == "simple"

    def test_generate_name_fallback(self, agent):
        name = agent._generate_name("fetch weather data from API")
        assert len(name) > 0
        assert name[0].isupper()


# --- Agent creation ---

class TestAgentCreation:
    def test_create_agent_writes_file(self, agent):
        result = json.loads(agent.perform(
            description="echo back the user query",
            name="EchoBack"
        ))
        assert result["status"] == "success"
        assert "EchoBack" in result["agent_name"]
        file_path = agent.agents_dir / "echo_back_agent.py"
        assert file_path.exists()

    def test_created_agent_has_correct_structure(self, agent):
        agent.perform(description="simple test agent", name="SimpleTest")
        code = (agent.agents_dir / "simple_test_agent.py").read_text()
        assert "class SimpleTestAgent(BasicAgent)" in code
        assert "def perform(self, **kwargs):" in code
        assert "super().__init__" in code

    def test_create_no_description_error(self, agent):
        result = json.loads(agent.perform(action="create"))
        assert result["status"] == "error"

    def test_create_duplicate_error(self, agent):
        agent.perform(description="first", name="Dupe")
        result = json.loads(agent.perform(description="second", name="Dupe"))
        assert result["status"] == "error"
        assert "already exists" in result["message"]

    def test_create_uses_query_as_description(self, agent):
        result = json.loads(agent.perform(query="an agent that counts words"))
        assert result["status"] == "success"


# --- Agent listing ---

class TestAgentListing:
    def test_list_empty(self, agent):
        result = json.loads(agent.perform(action="list"))
        assert result["status"] == "success"
        assert result["count"] == 0

    def test_list_excludes_core_agents(self, agent):
        # Create core agent files
        for name in ["basic_agent.py", "shell_agent.py", "manage_memory_agent.py",
                      "context_memory_agent.py", "learn_new_agent.py"]:
            (agent.agents_dir / name).write_text("# core")
        result = json.loads(agent.perform(action="list"))
        assert result["count"] == 0

    def test_list_includes_custom_agents(self, agent):
        (agent.agents_dir / "custom_agent.py").write_text("# Auto-generated by LearnNewAgent")
        result = json.loads(agent.perform(action="list"))
        assert result["count"] == 1
        assert result["agents"][0]["auto_generated"] is True

    def test_list_detects_non_generated(self, agent):
        (agent.agents_dir / "manual_agent.py").write_text("# hand-written agent")
        result = json.loads(agent.perform(action="list"))
        assert result["agents"][0]["auto_generated"] is False


# --- Agent deletion ---

class TestAgentDeletion:
    def test_delete_agent(self, agent):
        f = agent.agents_dir / "temp_agent.py"
        f.write_text("# temp")
        result = json.loads(agent.perform(action="delete", name="Temp"))
        assert result["status"] == "success"
        assert not f.exists()

    def test_delete_core_agent_blocked(self, agent):
        (agent.agents_dir / "basic_agent.py").write_text("# core")
        result = json.loads(agent.perform(action="delete", name="basic"))
        assert result["status"] == "error"
        assert "core" in result["message"].lower()

    def test_delete_nonexistent(self, agent):
        result = json.loads(agent.perform(action="delete", name="Ghost"))
        assert result["status"] == "error"

    def test_delete_no_name_error(self, agent):
        result = json.loads(agent.perform(action="delete"))
        assert result["status"] == "error"


# --- Code generation helpers ---

class TestCodeGeneration:
    def test_generate_tags(self, agent):
        tags = agent._generate_tags("fetch weather data from API")
        assert "weather" in tags
        assert "api" in tags

    def test_generate_tags_default(self, agent):
        tags = agent._generate_tags("do something generic")
        assert tags == ["custom"]

    def test_generate_extra_params_file(self, agent):
        params = agent._generate_extra_params("read a file from path")
        assert '"path"' in params

    def test_generate_extra_params_url(self, agent):
        params = agent._generate_extra_params("fetch from url")
        assert '"url"' in params

    def test_generate_extra_params_none(self, agent):
        params = agent._generate_extra_params("just do stuff")
        assert params == ""

    def test_generate_extra_imports_http(self, agent):
        imports = agent._generate_extra_imports("fetch from an API url")
        assert "urllib" in imports

    def test_generate_extra_imports_file(self, agent):
        imports = agent._generate_extra_imports("read a file")
        assert "pathlib" in imports

    def test_generate_extra_imports_none(self, agent):
        imports = agent._generate_extra_imports("just compute something")
        assert imports == ""

    def test_stdlib_modules_completeness(self, agent):
        stdlib = agent._stdlib_modules()
        assert "json" in stdlib
        assert "os" in stdlib
        assert "pathlib" in stdlib
        assert "subprocess" in stdlib
